spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  access-header: Authorization
  refresh-header: Refresh
  secret: shruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshrupp

client:
  host: .shrupp.net
  url: https://shrupp.net
# url: http://localhost:3000
  endpoint: success

#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: classpath:shruppssl.p12
#    key-store-password: zhsvnfkdlxm12
#    key-store-type: PKCS12
#    key-alias: shruppssl