spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1b8ff0d13c094175ce585c92e1fafac6
            client-secret: JTcr1zK63BVeiwCImZmQciLqY58Lw2wF
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  access-header: Authorization
  refresh-header: Refresh
  secret: shruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshruppshrupp

client:
  host: localhost
  url: https://localhost:3000
  endpoint: success